FROM node:9.11.1-alpine

# make the 'app' folder the current working directory
WORKDIR /app/

# copy both 'package.json' and 'package-lock.json' (if available)
COPY frontend/package*.json ./

# install project dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# build app for production with minification
WORKDIR /app/frontend

EXPOSE 8080

CMD [ "npm", "run", "serve"]