version: '3'

services:
  db:
    image: postgres
    networks: 
      - backend_network
  web:
    build: .
    command: >
      bash -c '
      cd backend/ &&
      python3 manage.py makemigrations &&
      python3 manage.py migrate --no-input &&
      python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code:ro
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks: 
      - nginx_network
      - backend_network

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./config/nginx/Dockerfile-dev
  #   ports:
  #     - 8000:80
  #   volumes:
  #     - ./config/nginx/dev-conf.d:/etc/nginx/conf.d
  #   depends_on:
  #     - web
  #     - db
  #   networks: 
  #     - nginx_network
  
  vue:
    build:
      context: .
      dockerfile: Dockerfile-vue-dev
    # command: >
    #       bash -c '
    #       cd frontend &&
    #       npm run serve'
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "8080:8080"
    networks:
      - nginx_network
    depends_on:
      - db

networks:
  nginx_network:
    driver: bridge
  backend_network:
    driver: bridge